### ISSUE TITLE
Doesn't work with BSD 14.0

### ISSUE THREAD

**Issue by iambenmitchell** [alexdupre/rtl_bsd_drv#2]
I'm using PFSense and I've just switched from CE to Plus which goes from BSD 12.0 to 14.0 and the driver has broken. I've gone to update it using the latest available from https://pkg.freebsd.org/FreeBSD:14:amd64/latest/All/realtek-re-kmod-198.00_1.pkg 

However, I get an error with something along the lines of "depends on kernel - not avail. or version mismatch"

Do you know how I can solve this? Thanks in advanced!

**Comment by alexdupre** [comment]
You likely need to build the package yourself from the ports tree or by cloning this repository.
